source 'https://rubygems.org'

gem 'rails', '3.2.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3'
gem "mysql2"
gem "rails3_acts_as_paranoid", "~> 0.2.0" # Rails3.2
gem 'dalli' # memcached client
gem 'redis', '~> 2.2.2'
gem 'redis-store', '~> 1.0.0.1'
gem 'capistrano_transmit'
gem 'kaminari', '~> 0.13.0'
gem 'resque', '~> 1.19.0'
gem 'resque-scheduler', '~> 1.9.9'
gem "slim"


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

#gem 'jquery-rails'
gem 'jquery-rails', "= 2.0.2"



# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano'

# To use debugger
# gem 'debugger'

group :development, :test do
  gem "rspec-rails"
  gem 'spork'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'factory_girl_rails'
  gem 'rails3-generators'
end